# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23ddbc7ab575b449428f62bac1b4e23fb778bf31124ff1904dd3ab4fb53a2e09c2c360f0d56d121fa29f20cf5941ee85d3a8e0c3ee916e03707249aa55ccc9c5

test:
  secret_key_base: 9df79600491492c1b5dbe54f1d5227b0e02528eaeafc6368e555c4c9efa4a577e967f4288b9549be12282b6b7ca8a61307bc0fe7a97a9171ef26681ee3267823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
